// "They show their work" (script v2, 2026-09-30): a Buddy's reply plays a video inline, 2 bars.
// Owner, 2026-10-05: "drop the section with the icons generated by buddy... trim it a little shorter":
// the emblem post, the emblem sheet and "Great work!" (footage B, 6 bars) are cut; they are in git
// history (432e886). That also takes the 16 readable workspace names off screen. Footage: FOOTAGE.md.
import type React from 'react';
import { AbsoluteFill, Series, staticFile, useCurrentFrame } from 'remotion';
import { Block, clamp01, INK } from './blocks';
import { CardEdit, FPS, type Key, STILL, type Shot, play, push, timeline } from './card';

export { FPS, HEIGHT, WIDTH } from './card';

const BEAT = 60 / 128;
const BAR = 4 * BEAT;

const REPLY = staticFile('2026-09-26_native-multimedia_2_reply-plays-video-inline.mp4');

type Part = {
  src: string;
  from: number;
  to: number;
  bars: number;
  note: string;
  camera: (seconds: number) => Key[];
  label?: string; // one line saying what the shot is
};

// The thread pane (x 2156–2974). The inline player sits at source rows 1038–1438.
const PANE: Shot = { focus: 1, x: 2156, w: 818, top: 600, scale: 1, ...STILL, ox: 0.55, oy: 0.64 };

const PARTS: Part[] = [
  {
    src: REPLY,
    from: 2.0,
    to: 2.0 + 2 * BAR,
    bars: 2,
    note: 'the reply, its video already playing inline',
    camera: (s) => [
      { t: 0, shot: PANE },
      { t: 0.8, shot: PANE },
      { t: s, shot: push(PANE, 1.3) },
    ],
  },
];

const frames = (p: Part) => Math.round(p.bars * BAR * FPS);
export const DURATION = PARTS.reduce((n, p) => n + frames(p), 0);

const Label: React.FC<{ text: string }> = ({ text }) => {
  const t = useCurrentFrame() / FPS - 0.5 * BEAT;
  return (
    <div style={{ position: 'absolute', left: 70, bottom: 70, opacity: clamp01(t / 0.1) }}>
      <Block text={text} u={t} size="md" fill={INK.cream} ink={INK.plate} rot={-1} />
    </div>
  );
};

const PartClip: React.FC<{ part: Part }> = ({ part }) => {
  const seconds = part.bars * BAR;
  const cuts = [play(part.from, part.to, (part.to - part.from) / seconds, part.note)];
  return (
    <AbsoluteFill>
      <CardEdit src={part.src} cuts={cuts} camera={part.camera(timeline(cuts).duration / FPS)} />
      {part.label ? <Label text={part.label} /> : null}
    </AbsoluteFill>
  );
};

export const ShowWork: React.FC = () => (
  <Series>
    {PARTS.map((p) => (
      <Series.Sequence key={p.note} durationInFrames={frames(p)}>
        <PartClip part={p} />
      </Series.Sequence>
    ))}
  </Series>
);
