#!/usr/bin/env bash
# v14 by cutting: "They show their work" loses its emblem shots (owner, 2026-10-05: "drop the section
# with the icons generated by buddy"), 8 bars → 2. No picture is rendered: the kept 2 bars are v13's
# first 2 bars of that scene, and everything after moves up by exactly 6 bars = 675 frames, so v14's
# picture is v13 frames 0–2828 + 3504–5775. Only the sound (the song re-timed) is rendered. Run from edit/.
set -euo pipefail
V13=../renders/v13-chain/launch-v13.mp4
node render.mjs render src/index.ts AssemblySound out/v14.wav --codec=wav --log=error
ffmpeg -y -loglevel error -i "$V13" -i out/v14.wav \
  -filter_complex "[0:v]trim=start_frame=0:end_frame=2829,setpts=PTS-STARTPTS[a];[0:v]trim=start_frame=3504:end_frame=5776,setpts=PTS-STARTPTS[b];[a][b]concat=n=2:v=1:a=0[v];[1:a]volume=-3.7dB[s]" \
  -map '[v]' -map '[s]' -c:v libx264 -crf 17 -preset slow -pix_fmt yuv420p -r 60 -c:a aac -b:a 256k -ar 48000 -movflags +faststart \
  out/launch-v14.mp4
ffprobe -v error -count_packets -select_streams v:0 -show_entries stream=nb_read_packets -of csv=p=0 out/launch-v14.mp4
