/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class BuddiesCore {
  /** Opens (or creates) the database. Refuses a file that is not a buddies-core database. */
  static open(path: string): Promise<BuddiesCore>
  post(actor: Actor, channel: ChannelRef, input: PostInput): Promise<PostWrite>
  answer(actor: Actor, input: AnswerInput): Promise<Post>
  getPost(actor: Actor, id: string): Promise<Post>
  openChannel(actor: Actor, channel: ChannelRef): Promise<Channel>
  listPosts(actor: Actor, query: PostQuery, before: Cursor | undefined | null, limit: number): Promise<PostPage>
  listPostsFrom(actor: Actor, query: PostQuery, postId: string, limit: number): Promise<PostPage>
  threadStats(actor: Actor, channelId: string, rootIds: Array<string>): Promise<Array<ThreadStat>>
  taskPosts(actor: Actor, taskId: string, before: Cursor | undefined | null, limit: number): Promise<PostPage>
  searchPosts(actor: Actor, workspaceId: string, query: SearchQuery, before: Cursor | undefined | null, limit: number): Promise<PostPage>
  inbox(actor: Actor, workspaceId: string): Promise<Inbox>
  markRead(actor: Actor, channelId: string, postId: string): Promise<void>
  followedThreads(actor: Actor, workspaceId: string, limit: number): Promise<FollowedThreads>
  markThreadRead(actor: Actor, rootId: string, postId: string): Promise<void>
  archivedChannels(actor: Actor, workspaceId: string): Promise<Array<Channel>>
  setChannelArchived(actor: Actor, channelId: string, archived: boolean, key: string): Promise<Channel>
  renameChannel(actor: Actor, channelId: string, name: string, key: string): Promise<Channel>
  createChannel(actor: Actor, input: ChannelInput): Promise<Channel>
  readDoc(actor: Actor, doc: DocRef): Promise<Doc | null>
  writeDoc(actor: Actor, input: DocWrite): Promise<Doc>
  listDocs(actor: Actor, buddyId: string, kind: DocKind): Promise<Array<Doc>>
  docRevisions(actor: Actor, docId: string): Promise<Array<DocRevision>>
  upsertTask(actor: Actor, write: TaskWrite): Promise<Task>
  getTask(id: string): Promise<Task>
  listTasks(query: TaskQuery): Promise<Array<Task>>
  taskCounts(workspaceId: string): Promise<Array<TaskCount>>
  enqueueRun(actor: Actor, input: EnqueueInput): Promise<Run>
  /** A foreground chat input with its text (the queued run is the owner's message). */
  enqueueChat(actor: Actor, input: ChatEnqueue): Promise<Run>
  /** The owner promoted a queued message: claimed before the conversation's other queued chats. */
  promoteChat(actor: Actor, turnId: string): Promise<Run>
  /** The owner cancelled a queued message. */
  cancelChat(actor: Actor, turnId: string): Promise<Run>
  /**
   * `channel_read {threadId, follow}`: subscribe (or, with no conversation, unsubscribe) this
   * Buddy's conversation to a thread and return its unread posts, marked read (deliveries.rs).
   */
  followThread(actor: Actor, rootId: string, conversationId: string | undefined | null, limit: number): Promise<ThreadUnread>
  /** The thread's unread posts for this Buddy, marked read (the follow wait's re-read). */
  catchUpThread(actor: Actor, rootId: string, limit: number): Promise<ThreadUnread>
  /** What a claimed delivery shows (deliveries.rs `compose`). */
  deliverPosts(runId: string): Promise<Delivery>
  /** The Buddies replying in a channel: its queued and running deliveries. */
  responding(channelId: string): Promise<Array<Responding>>
  /** The owner reruns a failed reply on another model (deliveries.rs `retry_delivery`). */
  retryDelivery(actor: Actor, postId: string, buddyId: string, config: RunConfig): Promise<Run>
  /** The holder is about to spawn (Pattern: durable-intake). */
  markExecuting(runId: string, leaseToken: string): Promise<Run>
  /** The provider default a model-less run config resolved to at claim (decision J). */
  recordRunModel(runId: string, leaseToken: string, model: string): Promise<Run>
  claimRun(budgets: RunBudgets, held: Array<RunHold>): Promise<Claim | null>
  renewRun(runId: string, leaseToken: string, leaseMs: number): Promise<Run>
  settleRun(runId: string, leaseToken: string, outcome: Outcome): Promise<Run>
  bindRun(runId: string, leaseToken: string, conversationId: string): Promise<Run>
  deferRun(runId: string, leaseToken: string, conversationId: string): Promise<Run>
  cancelRun(actor: Actor, runId: string): Promise<Run>
  retryRun(actor: Actor, runId: string, config: RunConfig | undefined | null, key: string): Promise<Run>
  createWorkspace(actor: Actor, input: WorkspaceInput): Promise<Workspace>
  createBuddy(actor: Actor, input: BuddyCreate): Promise<Buddy>
  updateBuddy(actor: Actor, input: BuddyUpdate): Promise<Buddy>
  getRun(id: string): Promise<Run>
  listRuns(query: RunQuery, limit: number): Promise<Array<Run>>
  listRunRows(reader: Actor, scope: ListScope, limit: number): Promise<Array<RunRow>>
  putSchedule(actor: Actor, input: ScheduleInput): Promise<Schedule>
  listSchedules(query: ListScope): Promise<Array<Schedule>>
  /** "Run now": the schedule fires at once (one silent chat run, no post). */
  fireSchedule(actor: Actor, scheduleId: string): Promise<Run>
  dueSchedules(now: string): Promise<Array<Run>>
  appendEvent(actor: Actor, input: EventInput): Promise<Event>
  listEvents(buddyId: string, beforeSeq: number, limit: number): Promise<Array<Event>>
  listWorkspaces(): Promise<Array<Workspace>>
  getBuddy(id: string): Promise<Buddy>
  listBuddies(workspaceId: string): Promise<Array<Buddy>>
  bindConversation(actor: Actor, input: ConversationInput): Promise<Conversation>
}

/**
 * Who acts. Stored as NULL (post author / channel creator) or the key `'owner'` (events, read
 * cursors, channel members).
 */
export type Actor =
  | { kind: 'owner' }
  | { kind: 'buddy'; id: string }

export interface AnswerInput {
  requestId: string
  body: string
  evidence: Array<string>
  /** The conversation that answered: provenance, and it subscribes to the request's thread. */
  fromConversationId?: string
  key: string
}

export interface Buddy {
  id: string
  workspaceId: string
  slug: string
  name: string
  role: string
  status: BuddyStatus
  managerId?: string
  provider?: string
  model?: string
  reasoningEffort?: string
  soulPath?: string
  maxActiveRuns: number
  createdAt: string
}

/** A patch: every absent field is unchanged. */
export interface BuddyChanges {
  name?: string
  role?: string
  manager?: ManagerRef
  provider?: Setting
  model?: Setting
  reasoningEffort?: Setting
  maxActiveRuns?: number
  status?: BuddyStatus
}

export interface BuddyCreate {
  workspaceId: string
  slug: string
  name: string
  role: string
  manager: ManagerRef
  provider?: string
  model?: string
  reasoningEffort?: string
  key: string
}

export type BuddyStatus = 'active' | 'archived'

export interface BuddyUpdate {
  buddyId: string
  changes: BuddyChanges
  key: string
}

export interface Channel {
  archivedAt?: string
  id: string
  workspaceId: string
  kind: ChannelKind
  createdBy: Actor
  createdAt: string
}

export interface ChannelInput {
  workspaceId: string
  name: string
  purpose: string
  key: string
}

/** What a channel is. Columns: `kind` plus (name, purpose) | member_key | task_id. */
export type ChannelKind =
  | { type: 'public'; name: string; purpose: string }
  | { type: 'direct'; members: Array<Actor> }
  | { type: 'task'; taskId: string }

/** Where a post goes. A direct or task channel is found, or created on first use. */
export type ChannelRef =
  | { kind: 'id'; id: string }
  | { kind: 'direct'; members: Array<Actor> }
  | { kind: 'task'; taskId: string }

export interface ChannelUnread {
  channel: Channel
  /** Posts by others after the reader's cursor (all of them when it has none). */
  unread: number
  /** The reader's cursor: the ordered id it has read through. Absent: it never read the channel. */
  lastReadOrd?: string
}

/** A foreground chat input, with its text: the queued run IS the owner's message. */
export interface ChatEnqueue {
  buddyId: string
  conversationId: string
  turnId: string
  /** The message as the host serialized it; never read by the crate. */
  body: string
}

export interface Claim {
  run: Run
  leaseToken: string
}

export interface Conversation {
  id: string
  buddyId: string
  workspaceId: string
  taskId?: string
  createdAt: string
}

export interface ConversationInput {
  id: string
  buddyId: string
  taskId?: string
}

/** Keyset position: posts strictly older than this ordered id. */
export interface Cursor {
  /** The ordered id of the last post of the previous page. */
  ord: string
}

export type Decision =
  | { kind: 'allowed' }
  | { kind: 'denied'; reason: string }

/** What a claimed delivery shows (deliveries.rs `compose`). */
export type Delivery =
  | { kind: 'posts'; posts: Array<Post>; unshown: number; subscribed?: string }
  | { kind: 'consumed' }

export interface Doc {
  id: string
  buddyId: string
  workspaceId: string
  scope: DocScope
  kind: DocKind
  name: string
  revision: number
  content: string
  updatedAt: string
}

export type DocKind = 'soul' | 'working' | 'long_term' | 'shared'

export interface DocRef {
  buddyId: string
  scope: DocScope
  kind: DocKind
  name: string
}

export interface DocRevision {
  docId: string
  revision: number
  content: string
  reason: string
  author: string
  provenance: string
  sha256: string
  createdAt: string
}

/**
 * Doc audience. Columns (scope_kind, scope_id); Buddy scope's id is the buddy, Workspace's the workspace.
 * Memory kinds (soul, working, long_term) are always Buddy-scoped: one per Buddy, read by every
 * turn kind and the owner's Memory tab. Only shared docs may be Workspace-scoped.
 */
export type DocScope =
  | { kind: 'buddy' }
  | { kind: 'workspace'; workspaceId: string }

export interface DocWrite {
  doc: DocRef
  content: string
  /** The revision the writer read; 0 when the doc does not exist yet. */
  baseRevision: number
  reason: string
  key: string
}

export interface EnqueueInput {
  buddyId: string
  input: RunInput
  conversationId?: string
  taskId?: string
  config?: RunConfig
}

export interface Event {
  seq: number
  at: string
  actor: string
  workspaceId: string
  buddyId?: string
  taskId?: string
  op: string
  payload: string
  idemKey?: string
  resultRef?: string
}

export interface EventInput {
  workspaceId: string
  op: string
  payload: string
  key?: string
  buddyId?: string
  taskId?: string
}

/** One card of the Threads view: a thread with at least one reply that the actor follows. */
export interface FollowedThread {
  channel: Channel
  root: Post
  replies: number
  /** Distinct authors, root author first. */
  participants: Array<Actor>
  tail: ThreadTail
}

/** Unread threads first, then by newest post. `more`: followed threads beyond `limit`. */
export interface FollowedThreads {
  threads: Array<FollowedThread>
  more: boolean
}

export interface Inbox {
  /** Requests addressed to the actor that still await its answer. */
  requests: Array<Post>
  /** The actor's own requests still awaiting someone else's answer. */
  waitingOn: Array<Post>
  /** The actor's channels in the workspace: every public one, its direct ones, and any it has read. */
  channels: Array<ChannelUnread>
  /** Followed threads in the workspace with a reply by someone else after the actor's thread cursor. */
  unreadThreads: number
}

export type ListScope =
  | { kind: 'buddy'; buddyId: string }
  | { kind: 'task'; taskId: string }
  | { kind: 'workspace'; workspaceId: string }

/** Who a buddy reports to. `Nobody` makes it a top-level buddy. */
export type ManagerRef =
  | { kind: 'nobody' }
  | { kind: 'buddy'; id: string }

/** A Buddy a post wakes. `config`: the owner's mention-chip pick, which the delivery turn runs on. */
export interface Mention {
  buddyId: string
  config?: RunConfig
}

export type Op = 'read_doc' | 'write_doc' | 'post' | 'read_channel' | 'search_posts' | 'create_channel' | 'archive_channel' | 'rename_channel' | 'write_task' | 'enqueue_run' | 'cancel_run' | 'retry_run' | 'write_schedule' | 'admin'

/** How a run ended, reported by the runner. */
export type Outcome =
  | { kind: 'complete'; text: string }
  | { kind: 'failed'; code: string; error: string }
  | { kind: 'cancelled'; reason: string }

export interface Post {
  id: string
  channelId: string
  author: Actor
  rootId?: string
  replyToId?: string
  taskId?: string
  purpose?: string
  body: string
  evidence: Array<string>
  request: RequestState
  conversationId?: string
  createdAt: string
  /** The post's ordered id (UUIDv7): threads, pages and read cursors order by it. */
  ord: string
  /** A reply also shown in its channel's feed ("Also send to #channel"). Always false at top level. */
  broadcast: boolean
}

export interface PostInput {
  /** `Request` needs a direct channel: the other members owe the answer. */
  kind: PostKind
  body: string
  purpose?: string
  evidence: Array<string>
  /** A reply in a thread: the post it responds to, in the same channel. Absent = a new top-level post. */
  replyToId?: string
  taskId?: string
  /**
   * The conversation the post was written from: provenance, and in a direct channel (or any
   * thread it follows) the conversation later posts by others there are delivered to.
   */
  fromConversationId?: string
  /**
   * The Buddies this post wakes (its @mentions; the Buddies of a DM the owner wrote in), each a
   * `deliver` run written in the post's own transaction (deliveries.rs `wake`).
   */
  mentions: Array<Mention>
  /**
   * A `Request` only: its recipients' runs execute with this instead of their profile (a
   * worker). Every recipient must be the author or report to it (`EnqueueRun`).
   */
  runConfig?: RunConfig
  /** A reply that also appears in the channel feed and its unread count. Invalid without `reply_to_id`. */
  broadcast: boolean
  key: string
}

export type PostKind = 'inform' | 'request'

export interface PostPage {
  posts: Array<Post>
  next?: Cursor
}

export type PostQuery =
  | { kind: 'channel'; channelId: string }
  | { kind: 'thread'; rootId: string }

/** A post write: the post, and whether this call created it (false: its key replayed). */
export interface PostWrite {
  post: Post
  created: boolean
}

/** A post's request lifecycle. Column `request` NULL is `None`; `Answered` names the answer post. */
export type RequestState =
  | { state: 'none' }
  | { state: 'awaiting' }
  | { state: 'answered'; answerId: string }
  | { state: 'cancelled' }
  | { state: 'failed' }

/** A queued or running delivery: "X is replying…" for a channel (deliveries.rs `responding`). */
export interface Responding {
  buddyId: string
  threadRootId: string
  startedAt: string
  running: boolean
}

export interface Run {
  id: string
  inputKey: string
  attempt: number
  input: RunInput
  buddyId: string
  workspaceId: string
  conversationId?: string
  taskId?: string
  taskEpoch?: number
  afterRunId?: string
  status: RunStatus
  deadline?: string
  leaseExpiresAt?: string
  outcome?: string
  errorCode?: string
  error?: string
  readyAt: string
  createdAt: string
  startedAt?: string
  endedAt?: string
  /** Absent: the run executes on its buddy's profile. */
  config?: RunConfig
  /**
   * A chat run's input (the owner's message, JSON the host wrote) while it can still be
   * requeued. The schema refuses a queued chat run without it (Pattern: durable-intake).
   */
  body?: string
  /**
   * When the holder was about to spawn (`mark_executing`). Absent: nothing ran yet, so a dead
   * holder's run goes back to the queue instead of being replayed or reported lost.
   */
  executingAt?: string
  /** A delivery's newest shown post, fixed by its first compose (deliveries.rs). */
  throughOrd?: string
}

/**
 * The two clocks a claim starts, kept apart because one number serving both killed owner chats
 * at 600 s (2026-09-10) and left dead holders' runs `running` for 24 h (2026-09-30).
 * `lease_ms`: how long the holder may go without renewing before the claim gate ends the run.
 * `chat_deadline_ms` / `turn_deadline_ms`: the absolute runtime budget of a foreground chat run
 * and of every other run, written to the run's `deadline` column. All three are required: the
 * host passes TURN_MAX_RUNTIME_MS for chats explicitly, never a default (AGENTS.md).
 * A zero turn_deadline_ms disables the background cutoff (deadline is NULL), not the lease.
 */
export interface RunBudgets {
  leaseMs: number
  chatDeadlineMs: number
  turnDeadlineMs: number
}

/**
 * How a run executes when it must not use its buddy's saved profile: a worker the buddy (or its
 * manager) spawned with a model of its choosing. Absent on a run = the profile. Values pass
 * through verbatim (provider-bespoke); the server checks them against its catalog before posting.
 */
export interface RunConfig {
  provider: string
  /**
   * Absent: the provider's default model, resolved by the host when the run is claimed and
   * written back onto the run (`record_run_model`), so the run says which model answered
   * (owner decision J, 2026-10-06). A "default" chip pick could not ride a run before this.
   */
  model?: string
  /** Absent: the provider's default effort. */
  reasoningEffort?: string
}

/** A run the caller's live turn executes; the claim gate renews it before expiring leases. */
export interface RunHold {
  runId: string
  leaseToken: string
}

/**
 * Why a run exists. Columns: (input_kind, input_id); the input_key is derived from it.
 *
 * Three live kinds (owner decisions H, I; delivery design §3): `chat` (an owner message, or with no
 * conversation a schedule fire, `fire_slot`), `post` (a request the Buddy owes) and `deliver` (a
 * post in a thread a conversation subscribes to). `reply`, `failure_notice` and `follow` were
 * folded into `deliver`; `schedule` is a silent `chat` again. Their ended rows stay `Retired`
 * history; the schema CHECK refuses a queued one, so it is never claimed.
 */
export type RunInput =
  | { kind: 'chat'; turnId: string }
  | { kind: 'post'; postId: string }
  | { kind: 'deliver'; postId: string }
  | { kind: 'retired'; inputKind: string; inputId: string }

export type RunQuery =
  | { kind: 'buddy'; buddyId: string }
  | { kind: 'conversation'; conversationId: string }
  | { kind: 'task'; taskId: string }
  | { kind: 'live'; workspaceId: string }

/** The bounded list projection. Full execution state and outcomes stay on `get_run`. */
export interface RunRow {
  id: string
  status: RunStatus
  input: RunInput
  taskId?: string
  requester?: Actor
  startedAt?: string
  endedAt?: string
  waiting?: RunWaiting
  /** The thread the run worked in, so a reader can open or resume it. */
  conversationId?: string
  /** What happened to a run that did not complete (e.g. `lease_expired`: the host or holder died mid-run and the claim gate ended it). */
  errorCode?: string
  error?: string
  /** What the run is FOR: the `purpose` of its post, when the reader may read that post's channel. */
  purpose?: string
  taskTitle?: string
}

export type RunStatus = 'queued' | 'running' | 'cancel_requested' | 'complete' | 'failed' | 'cancelled'

/**
 * Why a queued run cannot be claimed yet. This is derived from the claim predicate on every
 * read; it is never stored.
 */
export type RunWaiting =
  | { kind: 'not_before'; at: string }
  | { kind: 'buddy_archived' }
  | { kind: 'conversation_busy' }
  | { kind: 'pool_full'; active: number; max: number }
  | { kind: 'task_paused' }

export interface Schedule {
  id: string
  buddyId: string
  workspaceId: string
  taskId?: string
  name: string
  cron: string
  timezone: string
  prompt: string
  enabled: boolean
  nextRunAt?: string
  archivedAt?: string
  createdAt: string
}

export interface ScheduleInput {
  /** Absent = create. */
  id?: string
  buddyId: string
  taskId?: string
  name: string
  cron: string
  timezone: string
  prompt: string
  enabled: boolean
  key: string
}

/**
 * A structured post search. `text` is the grammar in `search.rs`; every filter narrows the
 * candidate set BEFORE paging and can only narrow it: readability is checked separately.
 * Empty `channels`/`from` = no filter (the lists are alternatives, ORed within a filter).
 */
export interface SearchQuery {
  text: string
  /** Channel ids or public channel names (a leading `#` is ignored). */
  channels: Array<string>
  /** Buddy ids, or `owner`. */
  from: Array<string>
  /** Inclusive lower bound: `YYYY-MM-DD` or an RFC 3339 timestamp. */
  after?: string
  /** Exclusive upper bound, same formats. */
  before?: string
  /** A thread's root post id: the root and its replies. */
  inThread?: string
}

/**
 * A profile field's new value: a named choice, or back to the server's default (column NULL).
 * A plain `Option<String>` patch could not say "clear" — absent already means "unchanged".
 */
export type Setting =
  | { kind: 'set'; value: string }
  | { kind: 'default' }

/** Whose resource an operation touches (the `target` of `authorize`). */
export type Subject =
  | { kind: 'owner' }
  | { kind: 'buddy'; id: string }
  | { kind: 'channel'; id: string }
  | { kind: 'run'; id: string }

export interface Task {
  id: string
  workspaceId: string
  ownerId: string
  parentId?: string
  title: string
  doneCriteria: string
  status: TaskStatus
  paused: boolean
  epoch: number
  nextAction?: string
  blockedReason?: string
  evidence: Array<string>
  position: number
  /** Workspace-home pin: 0 = not pinned, N > 0 = pinned, shown in ascending N. Top-level tasks only. */
  pin: number
  revision: number
  createdAt: string
  updatedAt: string
}

export interface TaskChanges {
  title?: string
  doneCriteria?: string
  status?: TaskStatus
  nextAction?: string
  blockedReason?: string
  evidence?: Array<string>
  paused?: boolean
  position?: number
  /** 0 unpins; N > 0 pins at order N (lower = earlier). Only a top-level task can be pinned. */
  pin?: number
  ownerId?: string
}

/** One Buddy's unfinished top-level tasks: `open` counts every one (blocked included). */
export interface TaskCount {
  buddyId: string
  open: number
  blocked: number
}

export type TaskQuery =
  | { kind: 'owner'; buddyId: string }
  | { kind: 'workspace'; workspaceId: string }
  | { kind: 'children'; parentId: string }

export type TaskStatus = 'open' | 'in_progress' | 'blocked' | 'review' | 'done' | 'cancelled'

/** A task write. Every field of `TaskChanges` is a patch: absent = unchanged. */
export type TaskWrite =
  | { kind: 'create'; ownerId: string; parentId?: string; title: string; doneCriteria: string; key: string }
  | { kind: 'update'; taskId: string; baseRevision: number; changes: TaskChanges; key: string }

/** A thread root's replies at a glance: the channel row's "3 replies · last reply 2m ago". */
export interface ThreadStat {
  rootId: string
  replies: number
  lastReplyAt: string
  /** The newest reply's ordered id: after the reader's cursor, the thread has something new. */
  lastReplyOrd: string
  lastReplyAuthor: Actor
}

/**
 * What a followed thread's card shows after its root: the fold (`hidden` replies) then `posts`,
 * oldest first. D = Unread (the replies after the cursor, at most 20) ⊕ CaughtUp (the last 2).
 */
export type ThreadTail =
  | { kind: 'unread'; hidden: number; posts: Array<Post> }
  | { kind: 'caught_up'; hidden: number; posts: Array<Post> }

/**
 * A thread's unread posts for one Buddy, oldest first: the newest `limit`, and how many older
 * unread ones were left out.
 */
export interface ThreadUnread {
  posts: Array<Post>
  unshown: number
}

export interface Workspace {
  id: string
  name: string
  rootPath: string
  createdAt: string
}

export interface WorkspaceInput {
  name: string
  rootPath: string
}
